# Generated by Django 4.2.4 on 2023-08-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="purpose",
            field=models.CharField(default="ssdsd", max_length=255),
            preserve_default=False,
        ),
    ]
