# Generated by Django 4.2.4 on 2023-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0004_alter_student_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="materials",
            field=models.ManyToManyField(blank=True, to="schoolapp.material"),
        ),
    ]
